custom: # 自定义的http启动端口，后续会重定向到https
  http-port: 13788
server:
  ip: 127.0.0.1
#  ip: 101.42.11.155
  port: 13799
  ssl:
    enabled: true
    key-store: classpath:ssl/rtcode.asia.jks
    key-store-password: 1fz85fcr68ikb9
    key-store-type: JKS

rtchat:
  # 名称
  name: 蝶语
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2023-2024
  # 文件路径 示例（ Windows配置E:/pictures/rtchat/，Linux配置 /home/rtchat/）
#  profile: E:/pictures/rtchat/
  profile: /home/rtchat/
  # 获取ip地址开关
  addressEnabled: true
  email:
    host: smtp.office365.com
    port: 587
    username: putongruwo@outlook.com
    password: Wrunt2002
  im:
    port: 9988

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/rtchat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    url: jdbc:mysql://101.42.11.155:3307/rtchat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
#    password: 123456
    password: qpqpalnzn53bjfbgfnf4353
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 1024MB
      # 总上传文件大小
      max-request-size: 10240MB
  rabbitmq:
#    host: localhost
    host: 101.42.11.155
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10
        max-concurrency: 20
  redis:
    host: 101.42.11.155
    port: 6380

mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.rt.entity
  mapper-locations: classpath:mapper/*Mapper.xml

mongo-plus:
  data:
    mongodb:
      host: 101.42.11.155
#      host: localhost
      port: 27017
      database: rtchat
      username: admin
      password: qpqpalnzn53bjfbgfnf4353
      connect-timeout-m-s: 50000
      wait-queue-timeout-m-s: 50000
      # 开启事务 @MongoTransactional
#      replica-set: rtchat
#  log: true

